#!/bash/bin
zipname="COS214_Practical3"
# zip the necessary h and cpp files 
find . -regextype posix-extended -regex "\./(bin|build|obj[^/]*)" -prune -o -regex -type f ".*/[A-Za-z0-9]+\.(cpp|h)" -exec zip -j "$zipname" {} +

./pdf #create the pdf submission file
zip -j "$zipname" makefile subbmission.pdf

echo "Created $zipname"
unzip -l "$zipname" #list zipped files 